parameters:
  - name: AllowUnitTests
    displayName: Allow unit tests
    type: boolean
    default : true

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ComptaClub.slnx'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotnetVersion: 'net10.0'
  environment: 'production'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: VSTest@2
  enabled: ${{parameters.AllowUnitTests}}
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      $(System.DefaultWorkingDirectory)\src\ComptaClub.Tests\bin\$(buildConfiguration)\$(dotnetVersion)\ComptaClub.Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled : false

- task: CmdLine@2
  displayName: Publish Blazor
  inputs:
    workingDirectory : $(System.DefaultWorkingDirectory)\src\ComptaClub.Blazor
    script: |
      dotnet publish -c $(buildConfiguration)
      cd $(System.DefaultWorkingDirectory)\src\ComptaClub.Blazor\bin\$(buildConfiguration)\$(dotnetVersion)\publish
      echo $(environment) > env.txt

- task: ArchiveFiles@2
  displayName: Create Zip to ArtifactStagingDirectory
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\src\ComptaClub.Blazor\bin\$(buildConfiguration)\$(dotnetVersion)\publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ComptaClub.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
