parameters:
  - name: AllowUnitTests
    displayName: Allow unit tests
    type: boolean
    default : true

trigger:
  batch: 'true'
  branches:
    include:
      - prod

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'ComptaClub.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  secureFile: 'comptaclubdev-ComptaClubDev-20230204.pfx',
  dotnetVersion: 'net7.0'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=false'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration

- task: DownloadSecureFile@1
  name: KeyvaultCertificat 
  displayName: Download KeyVault Certificate from library
  inputs:
    secureFile: '$(secureFile)'

- task: CopyFiles@2
  inputs:
    SourceFolder: "$(Agent.TempDirectory)"
    Contents: '$(secureFile)'
    TargetFolder: '$(Build.repository.LocalPath)\src'
    OverWrite: true

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  displayName: Publish Blazor
  inputs:
    workingDirectory : $(System.DefaultWorkingDirectory)\src\ComptaClub.Blazor
    script: |
      dotnet publish -c $(buildConfiguration)
      cd $(System.DefaultWorkingDirectory)\src\ComptaClub.Blazor\bin\$(buildConfiguration)\$(dotnetVersion)\publish
      echo $(environment) > env.txt

- task: ArchiveFiles@2
  displayName: Create Zip to ArtifactStagingDirectory
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\src\ComptaClub.Blazor\bin\$(buildConfiguration)\$(dotnetVersion)\publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ComptaClub.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'