trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: COMPTACLUB
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Debug'
- name: dotnetVersion
  value: 'net10.0'
- name: scalewayRegistry
  value: 'rg.fr-par.scw.cloud/appliman-registry'

steps:
- task: Bash@3
  displayName: 'Docker Login to Scaleway Registry'
  env:
    SCALEWAY_API_KEY: $(SCALEWAY_API_KEY)
  inputs:
    targetType: 'inline'
    script: |
      echo "Logging in to Scaleway Registry..."
      echo $(SCALEWAY_API_KEY) | docker login $(scalewayRegistry) -u nologin --password-stdin

- task: Bash@3
  displayName: 'Build and Push Docker ComptaClub Image'
  inputs:
    targetType: 'inline'
    script: |
      echo "Current directory:"
      pwd

      IMAGE_NAME="$(scalewayRegistry)/comptaclub"

      echo "Building Docker image: ${IMAGE_NAME}:$(Build.BuildId)"
      docker build \
        -f src/ComptaClub.Blazor/Dockerfile \
        -t ${IMAGE_NAME}:$(Build.BuildId) \
        -t ${IMAGE_NAME}:latest \
        .

      echo "Pushing Docker image with build ID: ${IMAGE_NAME}:$(Build.BuildId)"
      docker push ${IMAGE_NAME}:$(Build.BuildId)

      echo "Pushing Docker image with environment tag: ${IMAGE_NAME}:latest"
      docker push ${IMAGE_NAME}:latest

