# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '66875632-a62f-4652-b367-040b4f777d3e'
  imageRepository: 'comptaclub'
  containerRegistry: 'comptaclub20221115231703.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  variables:
    - group: docker
    - name: vaultTenantId
      value: $[variables.vaultTenantId]
    - name: vaultClientId
      value: $[variables.vaultClientId]
    - name: vaultClientSecret
      value: $[variables.vaultClientSecret]
    - name: comptaclubdev
      value: $[variables.comptaclubdev]

  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: AzureWebAppContainer@1
      displayName: Publish to Azure web app container
      inputs:
        azureSubscription: 'Consommation sur la plateforme Windows Azure(a1fc43e7-369d-4237-b75e-4b01bdb7be04)'
        appName: 'ComptaClub'
        containers: $(containerRegistry)/$(imageRepository):$(tag)
        appSettings: 
          ComptaClub__KeyVaultTenantId $(vaultTenantId)
          ComptaClub__KeyVaultClientId $(vaultTlientId)
          ComptaClub__KeyVaultClientSecret $(vaultClientSecret)
          ComptaClub__KeyVaultName $(vaultName)

