<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ComptaClub.Datas</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Scripts\ComptaClub\0001-CreateTable-Accounts.sql" />
    <None Remove="Scripts\ComptaClub\0002-CreateTable-Banks.sql" />
    <None Remove="Scripts\ComptaClub\0003-CreateTable-Documents.sql" />
    <None Remove="Scripts\ComptaClub\0004-CreateTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0005-CreateTable-Exercices.sql" />
    <None Remove="Scripts\ComptaClub\0006-CreateTable-Members.sql" />
    <None Remove="Scripts\ComptaClub\0007-CreateTable-RolesByUsers.sql" />
    <None Remove="Scripts\ComptaClub\0008-CreateTable-Users.sql" />
    <None Remove="Scripts\ComptaClub\0009-CreateTable-DocumentByEntities.sql" />
    <None Remove="Scripts\ComptaClub\0010-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0011-AlterTable-Exercice.sql" />
    <None Remove="Scripts\ComptaClub\0012-AlterTable-Exercice.sql" />
    <None Remove="Scripts\ComptaClub\0013-AlterTable-Bank.sql" />
    <None Remove="Scripts\ComptaClub\0014-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0015-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0016-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0017-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0018-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0019-AlterTable-Users.sql" />
    <None Remove="Scripts\ComptaClub\0020-AlterTable-Users.sql" />
    <None Remove="Scripts\ComptaClub\0021-AlterTable-Members.sql" />
    <None Remove="Scripts\ComptaClub\0023-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0024-CreateTable-AssociatedMemberListByEntryData.sql" />
    <None Remove="Scripts\ComptaClub\0025-AlterTable-AssociatedMemberListByEntryData.sql" />
    <None Remove="Scripts\ComptaClub\0026-AlterTable-Documents.sql" />
    <None Remove="Scripts\ComptaClub\0027-CreateTableDocumentContents.sql" />
    <None Remove="Scripts\ComptaClub\0028-AlterTable-Exercices.sql" />
    <None Remove="Scripts\ComptaClub\0029-CreateIncomeStatement.sql" />
    <None Remove="Scripts\ComptaClub\0030-AlterTableIncomeStatementItem.sql" />
    <None Remove="Scripts\ComptaClub\0031-AlterTable-Entries.sql" />
    <None Remove="Scripts\ComptaClub\0032-AlterTable-DocumentByEntity.sql" />
    <None Remove="Scripts\ComptaClub\0033-AlterTable-DocumentByEntity.sql" />
    <None Remove="Scripts\ComptaClub\0034-AlterTable-DocumentByEntity.sql" />
    <None Remove="Scripts\ComptaClub\0035-AlterTable-DocumentByEntity.sql" />
    <None Remove="Scripts\ComptaClub\0036-CreateTable-Clubs.sql" />
    <None Remove="Scripts\ComptaClub\0037-CreateTable-DataProtectionKey - Copy.sql" />
    <None Remove="Scripts\ComptaClub\0038-CreateTables-ForecastBudget.sql" />
    <None Remove="Scripts\ComptaClub\0039-AlterTable-Clubs.sql" />
    <None Remove="Scripts\ComptaClub\0040-AlterTable-Members.sql" />
    <None Remove="Scripts\ComptaClub\0041-AlterTable-Members.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Scripts\ComptaClub\0041-AlterTable-Members.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0040-AlterTable-Members.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0039-AlterTable-Clubs.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0037-CreateTable-DataProtectionKey - Copy.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0038-CreateTables-ForecastBudget.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0036-CreateTable-Clubs.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0003-CreateTable-Documents.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0031-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0035-AlterTable-DocumentByEntity.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0034-AlterTable-DocumentByEntity.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0033-AlterTable-DocumentByEntity.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0032-AlterTable-DocumentByEntity.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0030-AlterTableIncomeStatementItem.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0029-CreateIncomeStatement.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0028-AlterTable-Exercices.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0026-AlterTable-Documents.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0025-AlterTable-AssociatedMemberListByEntryData.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0023-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0024-CreateTable-AssociatedMemberListByEntryData.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0021-AlterTable-Members.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0020-AlterTable-Users.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0019-AlterTable-Users.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0018-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0017-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0016-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0015-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0014-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0013-AlterTable-Bank.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0012-AlterTable-Exercice.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0011-AlterTable-Exercice.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0010-AlterTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0009-CreateTable-DocumentByEntities.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0008-CreateTable-Users.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0007-CreateTable-RolesByUsers.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0006-CreateTable-Members.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0005-CreateTable-Exercices.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0004-CreateTable-Entries.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0027-CreateTableDocumentContents.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0002-CreateTable-Banks.sql" />
    <EmbeddedResource Include="Scripts\ComptaClub\0001-CreateTable-Accounts.sql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EFScriptableMigration" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ComptaClub.Datas\ComptaClub.Datas.csproj" />
  </ItemGroup>
</Project>