<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>644c6bdd-01bb-4b4e-8be7-3b4c7157e097</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	
  <ItemGroup>
    <ProjectReference Include="..\ComptaClub.Core\ComptaClub.Core.csproj" />
  </ItemGroup>

</Project>
