name: comptaclub

services:
  comptaclub:
    container_name: comptaclub
    image: rg.fr-par.scw.cloud/appliman-registry/comptaclub:latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ASPNETCORE_URLS=http://0.0.0.0:33001
      - ComptaClub__DatabaseProvider=${COMPTACLUB_DATABASE_PROVIDER:-MsSql}
      - ComptaClub__ConnectionString=${COMPTACLUB_CONNECTION_STRING-}
      - ComptaClub__SqliteConnectionString=${COMPTACLUB_SQLITE_CONNECTION_STRING-}
      - ComptaClub__AzureStorageConnectionString=${COMPTACLUB_AZURE_STORAGE_CONNECTION_STRING:?Define COMPTACLUB_AZURE_STORAGE_CONNECTION_STRING in .env}
      - ComptaClub__SmtpPassword=${COMPTACLUB_SMTP_PASSWORD:?Define COMPTACLUB_SMTP_PASSWORD in .env}
    volumes:
      - comptaclub-data:/app/data

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"

      # Route HTTP -> HTTPS
      - "traefik.http.routers.comptaclub-http.rule=Host(`compta.andernos-triathlon.club`)"
      - "traefik.http.routers.comptaclub-http.entrypoints=web"
      - "traefik.http.routers.comptaclub-http.middlewares=comptaclub-redirect@docker"

      # Route HTTPS
      - "traefik.http.routers.comptaclub.rule=Host(`compta.andernos-triathlon.club`)"
      - "traefik.http.routers.comptaclub.entrypoints=websecure"
      - "traefik.http.routers.comptaclub.tls=true"
      - "traefik.http.routers.comptaclub.tls.certresolver=letsencrypt"

      # Le port interne de l'app DANS le container
      - "traefik.http.services.comptaclub.loadbalancer.server.port=33001"

      # Middleware unique
      - "traefik.http.middlewares.comptaclub-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.comptaclub-redirect.redirectscheme.permanent=true"

networks:
  traefik-public:
    external: true
    name: traefik-public

volumes:
  comptaclub-data:
