name: comptaclub

services:
  comptaclub:
    container_name: comptaclub
    image: ghcr.io/appliman/comptaclub:latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ASPNETCORE_URLS=http://0.0.0.0:33001
      - ComptaClub__DatabaseProvider=${COMPTACLUB_DATABASE_PROVIDER:-Sqlite}
      - ComptaClub__ConnectionString=${COMPTACLUB_CONNECTION_STRING-}
      - ComptaClub__SmtpPassword=${COMPTACLUB_SMTP_PASSWORD:?Define COMPTACLUB_SMTP_PASSWORD in .env}
      - ComptaClub__AdminUserEmail=${COMPTACLUB_ADMIN_USER_EMAIL:?Define COMPTACLUB_ADMIN_USER_EMAIL in .env}
      - ComptaClub__ContactEmailAdress=${COMPTACLUB_CONTACT_EMAIL_ADDRESS:?Define COMPTACLUB_CONTACT_EMAIL_ADDRESS in .env}
      - ComptaClub__ContactName=${COMPTACLUB_CONTACT_NAME:?Define COMPTACLUB_CONTACT_NAME in .env}
      - ComptaClub__SmtpHost=${COMPTACLUB_SMTP_HOST:?Define COMPTACLUB_SMTP_HOST in .env}
      - ComptaClub__SmtpPort=${COMPTACLUB_SMTP_PORT:?Define COMPTACLUB_SMTP_PORT in .env}
      - ComptaClub__SmtpUserName=${COMPTACLUB_SMTP_USER_NAME-}
      - ComptaClub__SmtpEnableSsl=${COMPTACLUB_SMTP_ENABLE_SSL:-true}
      - ComptaClub__OtlpEndpoint=${COMPTACLUB_OTLP_ENDPOINT:?Define COMPTACLUB_OTLP_ENDPOINT in .env}
    volumes:
      - comptaclub-data:/app/data

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"

      # Route HTTP -> HTTPS
      - "traefik.http.routers.comptaclub-http.rule=Host(`${COMPTACLUB_DOMAIN:?Define COMPTACLUB_DOMAIN in .env}`)"
      - "traefik.http.routers.comptaclub-http.entrypoints=web"
      - "traefik.http.routers.comptaclub-http.middlewares=comptaclub-redirect@docker"

      # Route HTTPS
      - "traefik.http.routers.comptaclub.rule=Host(`${COMPTACLUB_DOMAIN:?Define COMPTACLUB_DOMAIN in .env}`)"
      - "traefik.http.routers.comptaclub.entrypoints=websecure"
      - "traefik.http.routers.comptaclub.tls=true"
      - "traefik.http.routers.comptaclub.tls.certresolver=letsencrypt"

      # Le port interne de l'app DANS le container
      - "traefik.http.services.comptaclub.loadbalancer.server.port=33001"

      # Middleware unique
      - "traefik.http.middlewares.comptaclub-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.comptaclub-redirect.redirectscheme.permanent=true"

networks:
  traefik-public:
    external: true
    name: traefik-public

volumes:
  comptaclub-data:
